### ISSUE TITLE
DPL-378 - Limber - Modify Duplex Seq and Targeted Nanoseq pipelines to allow for selective progression of samples beyond the AL Lib Dil step

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1077]
**User story**
As a TeamLead/Laboratory Scientist, we require the ability to filter out some of the samples on the plate by putting zero in the sample volume field at upload of the customer file within Limber when needing to create the LTN & LDS AL Lib Dil plate
(‘Sample volume’ , [Example_File_B.csv](https://github.com/sanger/limber/files/8729216/Example_File_B.csv))

**Who are the primary contacts for this story**
Sara W

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Allow upload of customer file on creation of the AL Lib Dil plate with a zero value within the sample field
- [x] Samples with a zero sample_volume should not be included in the AL Lib Dil plate (be filtered out)
- [x] Multiple AL Lib Dil plates may be created from the same AL Lib plate with different selections of wells
- [x] The customer file needs to include at least one additional field 'Hyb Panel' (bait library) (and others may be required see story https://github.com/sanger/limber/issues/1074). The file may need to be converted to Excel to give a Hyb panel dropdown with specific options for the customer (this will increase the cost of the story as it's currently built as a csv).
- [x] Existing charge and pass step needs to be moved earlier to the AL Lib plate.
- [x] A new automated submission with a new submission template and request type should be generated on creation of the AL Lib Dil plate, for the steps between AL Lib Dil through to Lib PCR XP, with a new charge and pass step on the PCR XP plate.

**Dependencies**
This story is blocked by the following dependencies:
- #1078 

**Additional context**
See comments below.

**Comment by andrewsparkes** [comment]
The sample volume is required because this step is performing a binning calculation by volume to determine the number of pcr cycles required and position the sample in the next plate accordingly (see PcrCyclesBinnedPlate creator in Limber).
What should that calculation and positioning code do if you upload a null volume, treat it as sample volume 0?

**Comment by andrewsparkes** [comment]
See file app/models/labware_creators/pcr_cycles_binned_plate/csv_file/row.rb

```
@sample_volume = @row_data[sample_volume_column]&.strip&.to_f

validate :sample_volume_within_expected_range?

def sample_volume_within_expected_range?
    in_range?('sample_volume', sample_volume, @row_config.sample_volume_min, @row_config.sample_volume_max)
end
```

And in the purpose configs where labware creator is PcrCyclesBinnedPlate:
```
:sample_volume_min: 0.2
:sample_volume_max: 50.0
```

We could change the minimum in the config to be zero rather than 0.2, and also if the field is null in the file we could default it to a zero value.

**Comment by andrewsparkes** [comment]
Discussion from meeting on 1st June:
They do want to filter out certain samples from moving forward into the next plate at the creation of the AL Lib Dil plate. Potentially they will then cycle back and put these missed samples forward at a later date (customer decision essentially).
If we move the charge and pass forward from the XP to the AL Lib step, then the customer file information could be used to create an automated submission just for the chosen samples to go forward to the XP step. Information such as the number of PCR cycles and bait library (hyb panel) can then be stored on the request generated by that auto-submission.

**Comment by andrewsparkes** [comment]
NB. Same logic can be applied for both Duplex Seq and for Targeted Nanonseq.

**Comment by JamesGlover** [comment]
Customer supplies bait library at the stage. Can be persisted on the request itself, for presentation further downstream. Some difficulties with reducing friction when it comes to customer supplied data.

**Comment by JamesGlover** [comment]
From Zoom:

My suggestions of building the submission upfront from the AL LIbs presenter may not be the best option, and it may be better handled by the PcrCyclesBinnedPlate creator. While this does result in the awkward waiting for the aysnchronous submission building, it makes it much easier to find the requests you need to hook the new plate to, and eliminates the need for any disambiguation.

Worth noting: I think there is a way to set-up submissions to build synchronously. I don't think this is exposed via the API currently, but it might simplify things.

**Comment by andrewsparkes** [comment]
From Catarina,
Example files and processes.
[Process workflow TNano.xlsx](https://github.com/sanger/limber/files/8871755/Process.workflow.TNano.xlsx)
[Process workflow DupSeq.xlsx](https://github.com/sanger/limber/files/8871756/Process.workflow.DupSeq.xlsx)
[B_TNano template to rearray.xlsx](https://github.com/sanger/limber/files/8871757/B_TNano.template.to.rearray.xlsx)
[A_TNano template for AL-Lib Dil PCR Cycles.xlsx](https://github.com/sanger/limber/files/8871761/A_TNano.template.for.AL-Lib.Dil.PCR.Cycles.xlsx)

**Comment by andrewsparkes** [comment]
Without switching to an Excel solution for the customer upload file this could be what's needed for this story:

In Sequencescape: 
-  for Dil to XP plate submission
    - create new request type [name TBC]
    - create new submission template

In Limber:
- in PcrCyclesBinnedPlate::CsvFile::Row in app/models/labware_creators/pcr_cycles_binned_plate/csv_file/row.rb
    - modify sample_volume_within_expected_range? validation to allow zero value or in range
    - add new field ‘Hyb Panel’ to csv for customer to fill in and validate against known bait libraries
- in PcrCyclesBinnedPlate::CsvFile in app/models/labware_creators/pcr_cycles_binned_plate/csv_file.rb
    - modify generate_well_details_hash to either filter out or (better) flag rows where sample_volume = 0 (and also where empty?)
    - well_details is then used by PcrCyclesBinnedPlate
- in PcrCyclesBinnedPlate labware creator in app/models/labware_creators/pcr_cycles_binned_plate.rb
    - if not using well flag change validation wells_have_required_information? that currently checks that all wells on source have rows in file, to remove that check (risky)
    - continue to use config limits for non-zero sample_volume values
    - consider adding validation that NO wells are now going forward e.g. if all sample_volumes set to zero (min = 1)
    - modify after_transfer! method to
        - to skip wells in well_details where flag is set
    - modify wells_have_required_information? to 
        - skip validation for well.pending? if flag is set
    - add Hyb Panel field to also be stored in well metadata
    - add creation of auto-submission for plates to XP step for the child plate with those wells going forward
        - do this before transfers, so can record submission id in the transfers
        - new auto-submission template (see SS story)
        - use new request type [see SS story]
        - consider the grouping of samples into orders, e.g. if we store pcr_cycles in the requests that is an order-level field so would need a different order per pcr_cycle bin, or e.g. if different bait libraries are likely on the same plate
        - consider visibility of submission process to user, it takes time (how is it done in Cardinal?)
- in PcrCyclesBinningCalculator in app/models/utility/pcr_cycles_binning_calculator.rb
    - modify various methods to filter out wells from well_details that have the zero sample_volume flag, we do not want to transfer them
- in pipelines and purpose configuration for Duplex Seq and Targeted Nanoseq
    - change pipeline to split out Dil to XP plate steps into separate section using new request type
    - add submission section to Dil plate purpose configuration (see heron LTHR Cherrypick for example? or Cardinal)
- in PcrCyclesBinnedPlatePresenter in app/models/presenters/pcr_cycles_binned_plate_presenter.rb
    - consider using request.pcr_cycles to decide what to display
- in RSpec and / or Integration Suite add testing for:
    - customer upload for plate where selecting some wells to go forward but not all (partial) [i.e. normal scenario]
    - customer upload has set all sample_volumes to zero [i.e. error]

**Comment by andrewsparkes** [comment]
Clarification from Sara W and Maisie F on some questions (from emails 6th July):

Q. Are all the samples in a given customer upload file for an AL Lib plate going to have the same Hyb panel (bait library)? Or could it differ between samples in the same upload? (wondering if this could be one field on the customer upload file rather than for every sample).
A. The hyb panel can differ between samples within a plate, and we have seen this for most plates to date. There are 3 custom panels validated for this process I think, and the Broad core exome panel.

Q. Would it be practical to give the customer a list of acceptable Hyb panels (e.g. via email) so they could cut and paste the one they want to use into the customer file field(s) rather than go to the extra effort of creating an Excel file with a dropdown list? We’d need to validate the Hyb panel name on processing the file upload so it would have to match the name in the database.
A. I think the copy and paste option actually sounds feasible. We would just need to make it clear to faculty exactly wait the hyb panels are called from our side , not just what they know them as

Q. Can you confirm again whether the ‘original plate’ you want in the merged file is the LDS/LTN Stock plate (as we said in the meeting) or the next plate which is the LDS/LTN Cherrypick plate (as it says in the DPL-376 story). Obviously the cherrypick plate could already have some rearrangement compared to the original source stock plate from the customer. (Guess it would be possible to have both if that helps.)
A. Yes from the LTN cherry-pick- so the LTN cherry-pick is the stock plate in essence, the plate purpose is just changed to allow for the submission and shearing , so faculty are fully aware of the posositons of samples as this is how they have submitted them

Q. What do you want the merged file to be called? i.e. what should the download button in Limber say? e.g.  ‘Download merged summary file’?
A. Yes this sounds good- Could we call, it ‘Download merged summary file for rearray’? Or some combination of those words)

**Comment by andrewsparkes** [comment]
Mostly done but waiting for story 376 to catch up before UAT.

**Comment by SujitDey2022** [comment]
Related work was de-prioritised for now
