### ISSUE TITLE
DPL-609 [BUG] In Limber, plates in the "LTHR-384 Lib PCR 1" and "LTHR-384 Lib PCR 2" columns of the "Heron -384 V2" Kanban board display date stamps of a few days BEFORE the users have created them.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#1220]
**Describe the bug**
[BUG] Plates in the "LTHR-384 Lib PCR 1" and "LTHR-384 Lib PCR 2" columns of the "Heron -384 V2" Kanban board display date stamps of a few days BEFORE the users have created them.

**To Reproduce**
Need to confirm if this applies to all plates in these columns - it seems to.

**Expected behaviour**
The date shown is the "creation" date of the plates in the database. However this does not tie in with what the user is expecting.
Is there something about the previous step that creates these plates earlier?

This may or may not be easily fixable. First task is to work out why this is happening.
 
**Screenshots**
See screenshot
![Screenshot 2022-12-19 090119](https://user-images.githubusercontent.com/66008413/208940901-c4030784-f487-48e1-8a3f-8c39bc63a56a.png)
Highlighted plates were created on the 18/12/2022.

**Additional context**
Ana G has reported this.

**Comment by TWJW-SANGER** [comment]
After discussing with Sara we would like to understand:

- What do the states _pending_, _passed_, and _created_ mean on the Kanban board ?
- The cards only display one date, which if any state does this date relate to?
- The lab would really like the displayed date on the card to relate to the start of the operation represented by the column on the plate. Do we have a way to know this? Does it map to one of the above states?

- Once we've clarified what data is available - let's go through possible options with Sara.

**Comment by andrewsparkes** [comment]
Possibly this is the timestamp of when the tag plate was created. The tag plate physically becomes the LTHR PCR plate, as samples are transferred into the tag from the parent plate at this step rather than a completely 'new' child plate being made. The 'child' plate (the tag plate + samples from parent) is given a new plate purpose and label. A quirk of how tagging is done.

**Comment by sdjmchattie** [comment]
Adam did notice and notify us that there were some cards in training that looked like they shared a heritage with cards in the right-most column.  The preference would be that those only appear once, but this also sounds like another requirement that may have low impact so we're going to go ahead with a production release and monitor for issues like that that could be raised as new tickets.

The other thing noted was that updated at dates were not always completely up to date in the training environment, but this is to be expected since training is not looking at the live production data.
