### ISSUE TITLE
DPL-655 As Heron Lab TL (AC) I would like to use the data displayed in the Limber Kanban view for the Heron pipeline as a data source so that I can create reports in Tableau (BP-Medium)

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#1236]
**User story**
As Heron Lab TL (AC) I would like to use the data displayed in the Limber Kanban view for the Heron pipeline as a data source so that I can create reports in Tableau

**Who are the primary contacts for this story**
Avi C

**Who is the nominated tester for UAT**
Avi C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Provide a reference for extracting Sample Plate and Timestamp data from MLWH reporting on the Heron-384 V2 pipeline (added from a related[ user-story](https://github.com/sanger/General-Backlog-Items/issues/258))
- [ ] Enable Tableau connection to a data representation of the Kanban views in Limber
- [ ] Ideally the solution would extend to all pipeline in Limber
- [ ] Ideally the data representation could be adapted to pipelines in other applications (Traction, STAN, etc)

**Dependencies**
This story is blocked by the following dependencies:
- #1221 

**Additional context**

**Comment by SujitDey2022** [comment]
The scope of the story - 'DPL-nnn Provide a reference for extracting Sample Plate and Timestamp data from MLWH reporting on the Heron-384 V2 pipeline' was only to investigate and share the reference for the requested data points with the requestor so that they can extract and generate the report on their end. 

I will add the story title in this story as an additional acceptance criterion for tracking purposes and archive the previous one.
