### ISSUE TITLE
DPL-869 Research DPL-811 (Transfer PBMC isolations into FluidX tube racks)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1360]
**Description**
Time-box to 2 days. 
Research some of the unknowns around the following group of stories:
- https://github.com/sanger/limber/issues/1314 
- https://github.com/sanger/limber/issues/1332
- https://github.com/sanger/limber/issues/1333
- https://github.com/sanger/limber/issues/1331

Some unknowns are:
- How easy will it be to extend existing "custom pooling" functionality to have a many to many relationship?
- Does it make sense for DPL-828 (additional source plate) to be done as a separate story, or should it be done at the same time as DPL-811?
- Can the existing bed verification code architecture cope with multiple sources **and** multiple destinations? 
- How can we adapt the bed verification code to cope with the requirement to store the tube rack barcode from the uploaded scan, and use that in the bed verification as the destination barcode?

**Who the primary contacts are for this work**
Katy, Andrew

**Comment by andrewsparkes** [comment]
**Re: bed verifications and many to many relationships**
There are a number of bed verification robot classes that allow for different variations of parent/child relationships. See Limber `app/models/robots/*`

One of these is `PoolingAndSplittingRobot`, this one does have a many:many relationship, used in the Combined LCM pipeline.
It is meant for pooling from multiple sources (LCM Stock plates) and creating multiple stamped copies of destination plates. The two destinations this one makes are of different purposes (as we need for 007).

So at first glance this sounds very similar if not identical to what we will need for 007.
It is for destination plates though, not tube racks.

If the labware creator that is triggered when you 'add' the child rack creates the rack with its barcode, and has a fluidx scan file upload step to connect up the tubes, then the tube rack barcode should be recognisable in bed verification maybe? 

Not clear yet how far we went with tube rack integration in Limber.
Tube racks are tricky as they can physically be re-used, unlike other labwares. They often have etched barcodes on them rather than labels that could be replaced. Using them needs some thought.
