### ISSUE TITLE
DPL-915-b Integration Suite test for cell counting

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1575]
**Describe the Housekeeping**
Implement the Integration Suite test for https://github.com/sanger/limber/issues/1389

**Blocking issues**
Blocked by https://github.com/sanger/sequencescape/issues/3900
(because the test won't be up and running until the above is finished)

**Additional context**
Split out from https://github.com/sanger/limber/issues/1389

**Comment by yoldas** [comment]
We already do the download of Celleca input files and upload of cell count data on the defrost plate in the integration suite test. We create the upload files by modifying the plate barcode with the defrost barcode in fixture files, such as scrna_defrost_count_1.csv to achieve that. 

That was added to make sure that cell count data is available on source wells going into pooling because it is one of the validated constraints of pooling. If cell count data is missing for any source wells, an error will be shown in Pools plate creation.

We could go further and fail some wells but we already have small input going into pooling. That is why we are not adding that.
