### ISSUE TITLE
Y24-109 As a team (PSD) we would like to rework the Limber ReadMe so that it is clearer how SequenceScape & Limber interact and are setup.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#1709]
**Describe the Housekeeping**
As a team (PSD) we would like to rework the Limber ReadMe so that it is clearer how SequenceScape & Limber interact and are setup.

**Acceptance Criteria**
- [x] The Setup instructions should set up one application and then another.
- [x] The Setup instructions should include an explanation of what is being done and why.
- [x] The Readme should clearly indicate that Limber depends on SequenceScape and there is not (hopefully) a two way relationship

**Additional context**
A number of developers have been confused by the existing instructions.
Time box to 2 days.

**Comment by TWJW-SANGER** [comment]
Guessing this is small due to time box. This might not be true, happy to be corrected.

**Comment by andrewsparkes** [comment]
There is a two-way relationship in some sense unfortunately.
Limber config has to define all the labware purposes it uses in pipelines. BUT sequencescape also has to define the initial labwares in a pipeline because it needs them to exist in order to link them to request types for submission templates. And those need to exist before Limber runs `config:generate`. So those same initial labware purposes are configured in two places and you have to be careful as SS runs first and generates the record in the database, but then Limber select that labware purpose from the database and adds additional Limber config it then persists in a file on the Limber server and it's this combination that is used in the Limber pipelines.
e.g. in SS set up MyStockPlate with flags `input` true, `stock` true. In Limber config you will also have MyStockPlate set up, additionally defining what Presenter, LabwareCreator and Printer classes it uses. If you then also set MyStockPlate `input` false, `stock` false in Limber, that would not count as SS had already inserted it in the database with different values. You need to double check the config for SS and Limber are in sync in these cases. And if changing something check the database values after deployments are as you intended.
