### ISSUE TITLE
GPL-431 See location of floating controls 

### ISSUE THREAD

**Issue by rl15** [sanger/limber#429]
**User story**
GPL-431 | As rep for R&D (Lesley S) we would like to see the location of positive and negative floating controls in Limber, so that we can prevent a plate progressing through the pipeline if contamination is detected during QC.

**Who the primary contacts are for this story**
Lesley S
Jamie L
Sara W
Adam F
Danni W

**Acceptance Criteria**
1. Can see on the Limber plate view which wells are positive controls and which wells are negative controls
    a) Ideally the wells would be a different colour and have '+ve' or '-ve' on them
    b) Ideally this would be visible when on the existing 'Summary' and 'Samples' tabs
    c) At minimum it should be displayed on the cDNA-XP plate, but ideally on all plates in the Heron pipeline.
2. (technical) Whether a sample is a control or not should be stored in a more robust way than using text in the 'Supplier sample name' column. This will be implemented in https://github.com/sanger/sequencescape/issues/2666, which blocks this story.

**Additional context**
We’re currently discussing tracking and monitoring of negative controls for the Heron project. Currently, the lab based staff are not able to see the location of these floating controls, which is making the detection of contamination during QC steps very difficult.

**Comment by JamesGlover** [comment]
Potential cheap solution:
1) Limber has a samples tab, which is supposed to display the names of samples on the plate and their wells. There may be a little bit of work to instate this properly as:
  a) I'm not sure we're showing the tab for 384 well plates
  b) Someone mentioned in passing that it was currently broken.
2) Our negative controls currently have distinct names.

Full support for controls would obviously be a good thing, but could be substantial. The above could prove a good interim solution.

**Further background**
Sequencescape does have a control flag on sample, but I'm not sure how or indeed if this is currently used. We'd also probably want this to have three values, rather than just two, to distinguish between samples, positive and negative controls.

**Comment by JamesGlover** [comment]
After a bit more research the control flag on sample does NOT appear to drive any behaviour, although is exposed in a handful of places (mostly WH and API). I believe historically it could be set by the customer via sample manifests, although this was removed around the time we migrated to the new manifest processing.

**Comment by JamesGlover** [comment]
Ahh, I see, the supplier sample name has been set to negative control, the sanger sample ids and sample names are variations on Heron9999999

**Comment by KatyTaylor** [comment]
[control fields updating script.txt](https://github.com/sanger/limber/files/4634700/control.fields.updating.script.txt)
