### ISSUE TITLE
GPL-917 Add bed verification to LCMB and make LCMB first class pipeline

### ISSUE THREAD

**Issue by rl15** [sanger/limber#665]
**Description**
Scope what would be required to add bed verification to LCMB process (make good) and then make LCMB first class pipeline (possibly one package of work) 

**Who the primary contacts are for this work**
Andrew
James
Harriet

**Knowledge or Stake holders**
Ben Farr
Liz Easthope
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Additional context or information**
Rich C wrote (Wednesday, 10 March 2021 at 10:10)

RnD commented that the LCMB line is only a partial workflow and they are aware that RnD and Lims support is needed produce a robust, production pipeline.

Stand up 10th March
Discussed stand up on 10th March and consensus (LIMS/R&D) was specification was incomplete and needs further work

Liz E wrote (09 March 2021 12:40)

I’d like to add a story to include bed verification in the LCMB library prep process.  Most of our processing in HTP have the bed verification, but the LCMB library prep doesn’t.  This product line has no up-front QC checks and is often a plate of irreplaceable material.  Having this additional check in place will provide an added measure of control to the process.

**Comment by harrietc52** [comment]
Thoughts:

Curently “partial workflow” - confirm what this means?
Want to “produce a robust, production pipeline” - confirm what this means?
“make LCMB” first class pipeline - confirm what this means?

Two steps:

1. Robot Bed Verification

Currently it is a "partial workflow”, is this because it doesnt have a bed verification step currently?
what are the robot steps involved (!and do they have corresponding robot steps? if not, need to add new bed details)
from and to which plates, on what beds (1 bed = 1 plate)

2. Pipeline

There isn't currently a LCMB pipeline file in Limber
But the “limber_lcmb” is currently part of the WGS pipeline and Custom Pool pipeline 
Think it wants to move LCMB into its own pipeline configuration 
What are the request types? -> Request types in SS for LCMB pipeline
Library pass? What is that?
What are the relationships for the LCMB pipeline/ what is the behavior of the plate purposes.
Is it similar to WGS, just skipping a few steps/ changing a few steps
One LCMB moved into own pipeline, remove limber_lcmb from pipelines which currently have it?
If initial plate purpose can do to more than one plate purpose, can use pipeline branches=es

pipeline config files:
each of the "relationships" in Pipeline config file, could have corresponding robot detailing to/from what beds
At run time Limber loads up all pipelines, and finds the pipeline that matches filter, then looks up plate in relationships

**Comment by harrietc52** [comment]
A few stories have come out of this research task:
Story 1: GPL-nnn Add bed verification for LCMB (via WGS pipeline) #701

**Comment by harrietc52** [comment]
[PMAP_0052_LCM_WGS_v0.1.pdf](https://github.com/sanger/limber/files/6310027/PMAP_0052_LCM_WGS_v0.1.pdf)

**Comment by harrietc52** [comment]
26.04.21 Stand up - James Mack said he will follow this up with Liz E
