### ISSUE TITLE
DPL-033 addition of a phiX control during library prep in Heron pipeline [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/limber#740]
**User story**
DPL_033 As stakeholder in Heron pipeline (Stef L) I would like enable the addition of a phiX control during library prep  to allows us to normalise the negative control and to thus pass more samples.

**Who are the primary contacts for this story**
Rich R
Sara S
Emma G
Naomi Park
Stef L

**Acceptance criteria**
To be considered successful the solution must allow:
 - [ ] A new NovaSeq sequencing pipeline dedicated only to Heron samples needs to be created. 
 - [ ] The prompt ‘add spike control’ should not be present in this inbox. 
 - [ ] The prompt ‘add spike control’ should instead appear when the pool tubes are created towards the end of the library prep. This is because phiX will be added during the sample pooling step
- [ ] The phiX must be registered such that it demultiplexes as tag 888 on the NPG QC page. 

References
This is part of a change control process (028/21)

**Additional context**

Customer's original story:
The Heron pipeline is being modified to enable the addition of phiX during the pooling step. The addition of phiX will allow us to normalise the read number in the negative control and thus to reduce the number of failed samples. To enable this I (Stef L, Tris B, Team Heron) require the following changes to be made to the Heron LIMS pipeline:

[Heron_phiX_LIMS story.docx](https://github.com/sanger/limber/files/6614562/Heron_phiX_LIMS.story.docx)

**Comment by JamesGlover** [comment]
Details of PhiX:

PhiX is usually added in the sequencing pipeline as part of the AddSpikedInControlTask. This involves:
- Looking up the PhiX by barcode
- Adding the PhiX asset as a parent to the lane
- The PhiX does *NOT* actually get added as an aliquot in the lane (I think this is because PhiX addition actually predates multiplexing)

When the batch.xml and flowcell_io look up the PhiX they use the relationship `spiked_in_buffer` which finds any `SpikedBuffer` parents, the aliquot information etc is then pulled from there.

Changes:

Unfortunately the PhiX will now be added before the lane is generated, and instead the PhiX will need to be injected into the pool tube.

Solutions:

1) We could potentially just add PhiX as a parent of the tube, and then adjust `spiked_in_buffer_links` to include non-direct ancestors. However this will affect 175483 lanes which have multiple SpikedBuffer ancestors. (I believe most of these cases are due to SpikedBuffer itself sometimes having SpikedBuffer ancestors)

2) A more robust solution would be to switch to actually transferring the PhiX into the tube, and allowing transfers to persist it downstream. This would require:
- Either migration of historic data, or a fallback mechanism if PhiX is not present
- Some means of easily identifying PhiX that has been added as a control, such that entity_type can be set to 'library_indexed_spike'/'library_control' as appropriate. (Rather than 'library_indexed'/'library' as with standard samples. We *do* have `PhiX.sample` which may be useful here. (Although it will be worth checking that we don't have `PhiX.sample` running as a standard sample anywhere)
- spiked_phix_barcode is usually pulled straight from the SpikedBuffer `spiked_in_buffer&.human_barcode`. I don't actually know the best way to get this is we transfer the aliquots in, as the library_id points back at the stock. (And we can't fix this without changing historical data)

Other issues:
- A new NovaSeq pipeline would probably need to be backed by new request types and updated heron submisison templates to reduce risk of accidentally processing samples via the wrong pipeline.
- The new pipeline approach feels somewhat restricted, and it would feel cleaner to detect the spiked in controls, and dynamically change the behaviour of the step.
- Annoyingly previous convention was to append (spiked in controls) to pipelines with controls, and omit it on those without. But by the time NovaSeq went live, controls were spiked into all pipelines, so this was felt to be redundant. :(

**Comment by JamesGlover** [comment]
```sql
#Detect multiple PhiX ancestors
SELECT labware.id, COUNT(DISTINCT phix.id) FROM labware 
LEFT OUTER JOIN asset_links ON asset_links.descendant_id = labware.id
LEFT OUTER JOIN labware AS phix ON phix.id = asset_links.ancestor_id
WHERE labware.sti_type = 'Lane::Labware'
GROUP BY labware.id
HAVING COUNT(DISTINCT phix.id) > 1
```

**Comment by JamesGlover** [comment]
Don't appear to have any PhiX in lanes as a 'normal' sample:
```
SELECT receptacles.sti_type, labware.sti_type, COUNT(aliquots.id) FROM receptacles
LEFT OUTER JOIN aliquots ON aliquots.receptacle_id = receptacles.id
LEFT OUTER JOIN labware ON labware.id = receptacles.labware_id
WHERE aliquots.sample_id = 1255141
GROUP BY receptacles.sti_type, labware.sti_type
```

sti_type   | sti_type     | COUNT(aliquots.id) |
-----------|--------------|--------------------|
Receptacle | LibraryTube  | 230                |
Receptacle | SampleTube   | 2                  |
Receptacle | SpikedBuffer | 6024               |

**Comment by JamesGlover** [comment]
We *do* have 5  `SpikedBuffer` tubes containing a sample other than `PhiX.sample`
```
SELECT aliquots.sample_id, COUNT(labware.id) FROM receptacles
LEFT OUTER JOIN aliquots ON aliquots.receptacle_id = receptacles.id
LEFT OUTER JOIN labware ON labware.id = receptacles.labware_id
WHERE labware.sti_type = 'SpikedBuffer'
GROUP BY aliquots.sample_id
```

sample_id | COUNT(labware.id) |
----------|-------------------|
NULL      | 1                 |
1081381   | 5                 |
1255141   | 6024              |

**Comment by neilsycamore** [comment]
These SampleTube outliers may be artefacts, there has been in the past issues with generating parent library tubes as the page used defaulted to sample tube in the drop down menu

**Comment by JamesGlover** [comment]
Sample '1081381' appears to be a PhiX variety, and has only appeared on a single lane (2141255) where its actually flagged as 'library_indexed' (ie. treated as though it isn't PhiX) already. So we don't need to worry about accidentally altering the behaviour here.

**Comment by KatyTaylor** [comment]
Screenshots of current place in Sequencing pipeline where PhiX control is added:
First task on batch screen (Novaseq pipeline):

![Screenshot 2021-07-28 at 16 28 24](https://user-images.githubusercontent.com/10407809/127351460-b9c3df5c-0982-4d6b-9982-a03a8d608fe6.png)

Scan barcode of SpikedBuffer tube:

![Screenshot 2021-07-28 at 16 28 37](https://user-images.githubusercontent.com/10407809/127351512-f5ee8d5d-1821-4ef9-ad92-352047c1faa8.png)

**Comment by KatyTaylor** [comment]
Looking into lanes that have more than one SpikedBuffer Tube ancestor, to see if it's safe to start identifying the SpikedBuffer of a lane as the most recently created of all the SpikedBuffer ancestors.

```
-- Lanes that have more than one SpikedBuffer ancestor, where the 'most recent' doesn't match the 'direct'
SELECT labware_id, num_phix_ancestors, most_recent_phix_id, direct_phix.id AS direct_phix_id

FROM 
(
  SELECT labware.id AS labware_id, COUNT(DISTINCT phix.id) AS num_phix_ancestors, MAX(phix.id) AS most_recent_phix_id
  
  FROM labware 
  
  LEFT OUTER JOIN asset_links ON asset_links.descendant_id = labware.id
  LEFT OUTER JOIN labware AS phix ON phix.id = asset_links.ancestor_id

  WHERE labware.sti_type = 'Lane::Labware'
    AND phix.sti_type = 'SpikedBuffer'
    
  GROUP BY labware.id
  HAVING COUNT(DISTINCT phix.id) > 1
) AS phix_ancestors

JOIN asset_links AS al_direct ON al_direct.descendant_id = labware_id AND al_direct.direct = true
JOIN labware AS direct_phix ON direct_phix.id = al_direct.ancestor_id AND direct_phix.sti_type = 'SpikedBuffer'

WHERE most_recent_phix_id <> direct_phix.id;
-- 278 rows
```

```
-- Lanes that have more than one SpikedBuffer ancestor, where the 'most recent' is not also 'direct'
-- A lot of the above rows are explained by the Lane having >1 'direct' SpikedBuffer tube
SELECT labware_id, num_phix_ancestors, most_recent_phix_id, al_most_recent.direct AS is_direct

FROM 
(
  SELECT labware.id AS labware_id, COUNT(DISTINCT phix.id) AS num_phix_ancestors, MAX(phix.id) AS most_recent_phix_id
  
  FROM labware 
  
  LEFT OUTER JOIN asset_links ON asset_links.descendant_id = labware.id
  LEFT OUTER JOIN labware AS phix ON phix.id = asset_links.ancestor_id

  WHERE labware.sti_type = 'Lane::Labware'
    AND phix.sti_type = 'SpikedBuffer'
    
  GROUP BY labware.id
  HAVING COUNT(DISTINCT phix.id) > 1
) AS phix_ancestors

JOIN asset_links AS al_most_recent ON al_most_recent.descendant_id = labware_id AND al_most_recent.ancestor_id = most_recent_phix_id

WHERE al_most_recent.direct = false;
-- 32 rows (all SpikedBuffer tube 13232535)
```

**Comment by KatyTaylor** [comment]
Technical tasks:
- [ ] Modify NPG interfaces (MLWH flowcell and batch xml) to allow indirect SpikedBuffer ancestors of lanes, as well as direct parents
- [ ] Modify V1 API to accept multiple parents for a tube (for Limber tube creation)
- [ ] Limber interface to allow PhiX tube scanning
- [ ] Tweak integration suite test for Heron pipelines
- [ ] Sequencescape pipeline - without PhiX addition
